repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: no-commit-to-branch  # prevent direct commits to main branch
  - id: check-yaml
    args: ['--unsafe']
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: local
  hooks:
  - id: lint
    name: lint
    entry: make lint
    types: [python]
    language: system
    pass_filenames: false
  - id: typecheck
    name: typecheck
    entry: make typecheck
    types: [python]
    language: system
    pass_filenames: false
  - id: spellcheck
    name: spellcheck
    entry: make spellcheck
    types: [text]
    language: system
    pass_filenames: true
